In [5]:
import numpy as np

#Создаем свой массив

In [7]:
x = np.arange(12).reshape((3,4))
#Наш массив
#array([[ 0,  1,  2,  3],
#       [ 4,  5,  6,  7],
#       [ 8,  9, 10, 11]])
x.dtype 
#вывод
#dtype('float64')

dtype('float64')

#методы применяются по умному, сразу ко всем элементам массива

In [12]:
x = np.array([1, 2, 3], float)
x
#вывод
#array([ 1.,  2.,  3.])

array([1., 2., 3.])

# вывод типа массива (число с повышенной разрядностью, не целое в данном случае!)

In [13]:
x.dtype 
#вывод
#dtype('float64')

dtype('float64')

#Создание массива и просмотр его различных параметров.

In [16]:
a = np.arange(15).reshape(3, 5)
a
#array([[ 0,  1,  2,  3,  4],
#       [ 5,  6,  7,  8,  9],
#       [10, 11, 12, 13, 14]])
a.shape
#(3, 5)
a.ndim
#2
a.dtype.name
#'int64'
a.itemsize
#8
a.size
#15
type(a)
#<class 'numpy.ndarray'>#
b = np.array([6, 7, 8])
b
#array([6, 7, 8])
type(b)
#<class 'numpy.ndarray'>

numpy.ndarray

#Другой способ создания массива в нампи

In [17]:
a = np.array([2,3,4])
a
#array([2, 3, 4])

array([2, 3, 4])

#Так же можно создать и матрицу с числами с плавающей точкой.

In [18]:
b = np.array([1.2, 3.5, 5.1])
b.dtype
#dtype('float64')

dtype('float64')

#Альтернативный способ создания массива нампи

In [19]:
b = np.array([(1.5,2,3), (4,5,6)])
b
#array([[1.5, 2. , 3. ],
#       [4. , 5. , 6. ]])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

#Так же можно и создать массив комплексных чиселок.

In [20]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c
#array([[1.+0.j, 2.+0.j],
#       [3.+0.j, 4.+0.j]])

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

#Создание матрицы (нулевой)

In [24]:
np.zeros((3, 4))
#array([[0., 0., 0., 0.],
#       [0., 0., 0., 0.],
#       [0., 0., 0., 0.]])
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified
#array([[[1, 1, 1, 1],
#        [1, 1, 1, 1],
#        [1, 1, 1, 1]],
#       [[1, 1, 1, 1],
#        [1, 1, 1, 1],
#        [1, 1, 1, 1]]], dtype=int16)
np.empty( (2,3) )

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

Создание массива от х до у с разбиением на необходимое количество частей

In [25]:
np.linspace( 0, 2, 9 ) 
#array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Операции сравнения работают с каждым конкретным элементом массива.

Так же работают тригонометрические операции.

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b
#array([0, 1, 2, 3])
c = a-b
c
#array([20, 29, 38, 47])
b**2
#array([0, 1, 4, 9])
10*np.sin(a)
#array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])
a<35
#array([ True,  True, False, False])

И еще парочка мега полезных методов

In [26]:
x = np.arange(0,10,2)
y = np.arange(5)
m = np.vstack([x,y])
m


xy = np.hstack([x,y])
xy

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])